# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
