# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20170216_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('information', models.TextField(default='Normal category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
